import "dotenv/config";
import "express-async-errors";
import cors from "cors";
import express from "express";
import rateLimit from "express-rate-limit";
import helmet from "helmet";
import { requireAuth } from "./auth";
import { errorHandler } from "./http";
import { admin } from "./routes/admin";
import { orders } from "./routes/orders";
import { pub } from "./routes/public";
const app = express();
app.use(helmet());
app.use(cors({ origin: process.env.FRONTEND_URL }));
app.use(express.json());
app.use(rateLimit({ windowMs: 60_000, limit: 120 }));
app.use(pub);
app.use(orders);
app.use("/admin", requireAuth, admin);
app.use(errorHandler);
app.listen(Number(process.env.PORT) || 4000, () => console.log("API de Mimbela lista"));
